### ISSUE TITLE
CMOR-3.2.5 tag breaks getGitInfo

### ISSUE THREAD

**Issue by durack1** [durack1/durolib#17]
The hyphenated tag [`CMOR-3.2.5`](https://github.com/WCRP-CMIP/CMIP6_CVs/tags) breaks the current tag extract code

@dnadeau4 pinging you here

**Comment by dnadeau4** [comment]
I delete the tag a push a new one 3.2.5

**Comment by durack1** [comment]
@dnadeau4 thanks, I'll need to revisit this when we implement the changes planned in WCRP-CMIP/CMIP6_CVs#28
